---
- name: Ensure git and make are installed
  become: true
  package:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - make

- name: Clone awx-operator repo
  become: true
  git:
    repo: "https://github.com/ansible/awx-operator.git"
    dest: "./awx-operator"
    version: "tags/{{ awx_deploy_version }}"
    force: yes

- name: Run make deploy
  become: true
  command: make deploy
  args:
    chdir: "./awx-operator"

- name: Create kustomization.yaml
  become: true
  copy:
    dest: "./awx-operator/kustomization.yaml"
    content: |
          apiVersion: kustomize.config.k8s.io/v1beta1
          kind: Kustomization
          resources:
            - github.com/ansible/awx-operator/config/default?ref={{ awx_deploy_version }}
          images:
            - name: quay.io/ansible/awx-operator
              newTag: {{ awx_deploy_version }}
          namespace: {{ awx_deploy_namespace }}

- name: Apply operator manifests
  become: true
  command: oc apply -k .
  args:
   chdir: "./awx-operator"

- name: Create AWX instance manifest
  become: true
  copy:
    dest: "./awx-operator/awx-demo.yml"
    content: |
          apiVersion: awx.ansible.com/v1beta1
          kind: AWX
          metadata:
            name: {{ awx_deploy_instance_name }}
          spec:
            service_type: clusterip
            ingress_type: {{ awx_deploy_ingress_type }}

- name: Append AWX instance to kustomization.yaml
  become: true
  lineinfile:
    path: "./awx-operator/kustomization.yaml"
    line: "  - awx-demo.yml"
    insertafter: "resources:"
    state: present

- name: Deploy AWX instance
  become: true
  command: oc apply -k .
  args:
    chdir: "./awx-operator"

